---
# tasks file for lb-tier
- name: Install HAProxy
  yum:
    name: haproxy
    state: present

- name: Enable haproxy at boot
  service:
    name: haproxy
    enabled: yes
    state: started

- name: Configure haproxy to load balance over app servers
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg

- name: Start haproxy
  service:
    name: haproxy
    state: restarted
